### ISSUE TITLE
Got `NameError: uninitialized constant Redis::Classy` when running the task

### ISSUE THREAD

**Issue by apraditya** [shaiguitar/resque_stuck_queue#2]
I'm trying to setup with initializer in the README but I got NameError error when running the task. Here's the traceback:

```
** Invoke resque:stuck_queue (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute resque:stuck_queue
rake aborted!
NameError: uninitialized constant Redis::Classy
/Users/apraditya/.rbenv/versions/2.0.0-p598/gemsets/clients-web/gems/resque_stuck_queue-0.5.1/lib/resque_stuck_queue.rb:86:in `start'
/Users/apraditya/Projects/Client/clients-web/lib/tasks/resque_stuck_queue.rake:4:in `block (2 levels) in <top (required)>'
/Users/apraditya/.rbenv/versions/2.0.0-p598/gemsets/clients-web/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/Users/apraditya/.rbenv/versions/2.0.0-p598/gemsets/clients-web/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/Users/apraditya/.rbenv/versions/2.0.0-p598/gemsets/clients-web/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/Users/apraditya/.rbenv/versions/2.0.0-p598/gemsets/clients-web/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/Users/apraditya/.rbenv/versions/2.0.0-p598/gemsets/clients-web/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/apraditya/.rbenv/versions/2.0.0-p598/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Users/apraditya/.rbenv/versions/2.0.0-p598/gemsets/clients-web/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/apraditya/.rbenv/versions/2.0.0-p598/gemsets/clients-web/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/Users/apraditya/.rbenv/versions/2.0.0-p598/gemsets/clients-web/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/Users/apraditya/.rbenv/versions/2.0.0-p598/gemsets/clients-web/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/apraditya/.rbenv/versions/2.0.0-p598/gemsets/clients-web/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/Users/apraditya/.rbenv/versions/2.0.0-p598/gemsets/clients-web/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/Users/apraditya/.rbenv/versions/2.0.0-p598/gemsets/clients-web/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/Users/apraditya/.rbenv/versions/2.0.0-p598/gemsets/clients-web/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/Users/apraditya/.rbenv/versions/2.0.0-p598/gemsets/clients-web/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/Users/apraditya/.rbenv/versions/2.0.0-p598/gemsets/clients-web/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/apraditya/.rbenv/versions/2.0.0-p598/gemsets/clients-web/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/Users/apraditya/Projects/Client/clients-web/bin/rake:8:in `<top (required)>'
/Users/apraditya/.rbenv/versions/2.0.0-p598/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/apraditya/.rbenv/versions/2.0.0-p598/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
-e:1:in `<main>'
Tasks: TOP => resque:stuck_queue
```

Tried this:

`Resque::StuckQueue.config[:redis] = Resque.redis`

and this

`Resque::StuckQueue.config[:redis] = Redis.new(url: ENV['REDIS_URL']`

without any luck.  I'm using these gems:

redis (3.1.0)
redis-classy (2.2.0)
redis-mutex (4.0.0)
redis-namespace (1.5.1)
resque (1.25.2)
resque-scheduler (3.0.0)
resque_mailer (2.2.7)
resque_stuck_queue (0.5.1)

on Ruby 2.0.0p598.

**Comment by davek09** [comment]
redis-classy has apparently updated their syntax, see this upgrading memo: https://github.com/kenn/redis-classy/blob/master/UPGRADING.md
